BinaryStudioAcademy/bsa-2019-metrica

frontend/src/components/dashboard/home/ActiveVisitorsCard.vue

Temporarily indicated default values ​​of props. Must be changed during page building

Add active visitors card element

---

backend/app/Actions/Website/GetCurrentUserWebsiteAction.php

https://trello.com/c/TrXGfjUo/137-if-user-doesnt-have-a-website-the-error-occurs

fix UserWebsiteNotFoundException import

---

frontend/src/components/auth/UpdateProfileForm.vue

https://trello.com/c/Y0FruI45/142-edit-user-data-page-produces-bunch-of-exceptions

Fix: Edit user data page produces bunch of exceptions

---

frontend/src/components/auth/UpdateProfileForm.vue
frontend/src/services/validation.js

fix: edit user page

---

backend/app/Actions/Website/AddWebsiteAction.php

https://trello.com/c/PJoVE3Zl/149-master-of-adding-website-track-id-00000166-is-assigned-to-all-sites

Master of adding website: track id 00000166 is assigned to all sites

---

frontend/src/components/website/WebsiteForm.vue
frontend/src/components/website/adding_master/StepAddName.vue

set web site name restriction to not empty

---

frontend/src/components/common/LineChart.vue

fix line chart tooltip

---

frontend/src/components/common/PieChart.vue
frontend/src/components/utilites/Spinner.vue
frontend/src/pages/Visitors.vue
frontend/src/store/modules/visitors/getters.js
frontend/src/store/modules/visitors/state.js
frontend/src/store/modules/visitors/types/getters.js

https://trello.com/c/zPkrAlhs/216-link-piechart-to-vuex-state

add "pieChartData" to vuex modules

---

frontend/src/store/modules/visitors/actions.js

hot fix for https://trello.com/c/f9VWMjCQ/210-add-action-for-retrieving-tabledata

Add action for retrieving tableData (hot-fix)

---

backend/app/Repositories/EloquentTableSessionRepository.php
backend/tests/Feature/GetSessionsByParameterTest.php

fix session table filtering by browser parameter

---

backend/app/Actions/Sessions/GetAverageSessionByIntervalAction.php
backend/tests/Feature/ChartAverageSessionsApiTest.php

fix average session date return format to timestamp and fix error message

---

backend/app/Repositories/EloquentTableVisitRepository.php

fix return counter value for grouped visits data

---

backend/app/Repositories/EloquentTableNewVisitorsRepository.php
backend/tests/Feature/TableNewVisitorsApiTest.php

fix calculation of percentage for new visitors table

---

backend/app/Entities/Role.php
backend/app/Entities/User.php
backend/database/migrations/2019_09_01_124002_create_roles_table.php
backend/database/migrations/2019_09_01_130658_create_role_user_table.php

Feature/teams:add role entity, schema and relation

---

backend/app/Actions/Sessions/GetAverageSessionByIntervalAction.php

fix average session chart data endpoint

---

frontend/src/components/dashboard/visitors_flow/VisitorsFlowDropdown.vue

https://trello.com/c/EpiblAwV/344-add-dropdown-component-to-get-data-for-graph

add dropdown for visitors flow page

---

frontend/src/api/transformers.js
frontend/src/api/visitors/averageSessionsService.js

round avg session time to int

---

backend/app/Actions/Visits/GetVisitsDensityAction.php
backend/app/Entities/Visit.php
backend/app/Repositories/Contracts/VisitRepository.php
backend/app/Repositories/EloquentVisitRepository.php
frontend/src/components/dashboard/home/VisitsDensityWidget.vue

https://trello.com/c/s3aZDBFk/420-widget-users-by-time-of-day-widget-shows-incorrect-data

fix user by time of day widget

---

frontend/src/api/transformers.js

display page view exit rate in percentage

---

frontend/src/api/team.js

Fix/invite user email didn't send

---

frontend/src/api/page_views/averageTimeService.js

fix avg time on site for page views

---

frontend/src/components/dashboard/visitors_flow/VisitorsFlowDiagram.vue

https://trello.com/c/ryHU3Nr3/442-get-rid-of-animation-on-the-behavior-diagram-when-next-step-is-produced
https://trello.com/c/JQGAl3fu/443-when-click-on-transition-line-highlight-all-path

improve visitors flow diagram

---

backend/app/Actions/GeoLocation/GetGeoLocationItemsAction.php
backend/app/Entities/Session.php
frontend/src/api/geo_location/transformer.js
frontend/src/components/dashboard/geo_location/GroupedTable.vue

https://trello.com/c/y9c7Da36/428-script-geo-location-incorrect-data-in-table-and-on-map

fix geo-location page

---

frontend/src/store/modules/visitors/actions.js

round outcome new/returning visitors numbers

---

backend/app/Actions/Visitors/BounceRateAction.php

show data only for exist values

---

backend/app/Repositories/EloquentSessionRepository.php

fix date condition in selecting active session

---

frontend/src/api/page_views/averageTimeService.js
frontend/src/api/transformers.js
frontend/src/api/visitors/averageSessionsService.js

show avg time in minutes on line chart

---

frontend/src/components/dashboard/visitors_flow/VisitorsFlowDiagram.vue
frontend/src/pages/VisitorsFlow.vue

1. Fixed width of diagram and svg viewBox
2. Removed disabling of 'add step' button after click
3. Removed redundant lines of code
4. Fixed visualization of exit lines

fix visitors flow diagram

---

frontend/src/components/auth/SignUpForm.vue

add processing notification during sing up process

---

frontend/src/components/dashboard/visitors_flow/VisitorsFlowDiagram.vue

fix columns titles

---

frontend/src/components/dashboard/geo_location/MapList.vue

https://prnt.sc/p5kd1o
https://prnt.sc/p5kco8

add scrollbar for cases of a large number of items in the list

---

frontend/src/components/dashboard/home/ActiveVisitorsCard.vue
frontend/src/pages/PageViews.vue
frontend/src/store/modules/page_views/actions.js
frontend/src/store/modules/page_views/types/actions.js

Fix/dashbord: active user link leads to today data
